version: "3.9"

networks:
  mynetwork:
    driver: bridge

services:
  # MongoDB service
  mongo:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  # Backend service
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      DB_IP: mongodb
      DB_NAME: ${DB_NAME}
      PORT: ${BACKEND_PORT}
      FRONTEND_IP: nginx
      FRONTEND_PORT: ${NGINX_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    tty: true
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongo
    networks:
      - mynetwork

  # Frontend service
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
        BACKEND_IP: ${NGINX_IP}
        BACKEND_PORT: ${NGINX_PORT}

    tty: true
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - mynetwork

volumes:
  mongo_data:
