version: "3.9"

networks:
  mynetwork:
    driver: bridge

services:
  # MongoDB service
  mongo:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME_ARG}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD_ARG}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  # Backend service
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      LOGGER_LEVEL: ${LOGGER_LEVEL_ARG}
      DB_IP: mongodb
      DB_NAME: ${DB_NAME_ARG}
      PORT: ${BACKEND_PORT_ARG}
      FRONTEND_IP: ${NGINX_IP}
      FRONTEND_PORT: ${NGINX_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY_ARG}

    tty: true
    ports:
      - "${BACKEND_PORT_ARG}:${BACKEND_PORT_ARG}"
    depends_on:
      - mongo
    networks:
      - mynetwork

  # Frontend service
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PORT_ARG: ${FRONTEND_PORT_ARG}
        BACKEND_IP_ARG: ${NGINX_IP}
        BACKEND_PORT_ARG: ${NGINX_PORT}

    tty: true
    ports:
      - "${FRONTEND_PORT_ARG}:${FRONTEND_PORT_ARG}"
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - mynetwork

volumes:
  mongo_data:
